Fix find-by-pattern blocks indefinitely
nilenso/goose pull request #115
Opened 2023-06-27 03:44 UTC by chage

When the queue is empty, the cursor will start decrementing from 0 and will never stop at 0.
Since `car/lrange` allows negative values, I leave it unchanged as it is.

2023-06-27 12:43 UTC, olttwa commented
Hey @chage, thanks for reporting this bug.

The fundamental issue lies in stopping/terminal condition of `scan-seq`'s recursion: `(when-not (zero? next-cursor) (scan-seq ...))`

Changing the condition to `(when (< 0 next-cursor) (scan-seq ...)` should fix this bug.

This bug also caused `list-all-queues` to run indefinitely. Above fix solves that too.

2023-06-27 12:46 UTC, olttwa commented
@chage can you make 2 changes to your PR:
1. Add the new condition we discussed to `scan-seq`
2. Add a small test in `goose.brokers.redis.api-test` that ensures all Redis APIs recurring over empty list/queue/scheduled-sets return empty results and aren't blocking?

Post that, we can merge it. If you have any other thoughts, do let us know.

2023-06-27 12:48 UTC, olttwa requested changes
@chage can you make 2 changes to your PR:
1. Add the new condition we discussed to `scan-seq`.
2. Add a small test in `goose.brokers.redis.api-test` that ensures all Redis APIs recurring over empty list/queue/scheduled-sets return empty results and aren't blocking.

Post that, we can merge it. If you have any other thoughts, do let us know.

2023-06-28 08:04 UTC, chage commented
Thank you, @olttwa.
I will make the changes you mentioned.

But I don’t think `list-all-queues` has the same problem. Cause the `scan-fn` it used directly return the result of `car/scan`. And `SCAN` family of Redis will return `unsigned 64 bit number` ([doc](https://redis.io/commands/scan/#return-value)). Anyway, I will add test cases, too.

And I want to confirm that if I need to revert my current changes? Because they are redundant if I modified the condition of `scan-seq`.

2023-06-28 08:49 UTC, olttwa commented
@chage you're right about `list-all-queues`. I was experimenting by changing the `(zero? next-cursor)` to `(neg? next-cursor)`, and it was blocking for me then. It doesn't block with current setup.

I think we should modify the condition of `scan-seq` because that's the base recursion used by other functions. Your current changes will be redundant, so you can revert them.

2023-06-29 07:02 UTC, olttwa approved these changes

2023-06-29 07:13 UTC, merged